### ISSUE TITLE
Possible Issue with LRADC being tied to 3V3

### ISSUE THREAD

**Issue by xtacocorex** [NextThingCo/PocketCHIP-PCB#1]
In looking over the V1.0 PocketCHIP schematic while updating CHIP_IO to handle the IO names on the GPIO header.

It looks like LRADC on U14-10 is being tied to 3v3 and the 3v3 on U14-12 is being tied to ADC.

Please correct me if I'm wrong with this and have mis-interpreted the schematic.

**Comment by DurandA** [comment]
I second that. According to https://github.com/NextThingCo/CHIP-Hardware/blob/master/CHIP%5Bv1_0%5D/CHIP_v1_0_PINOUT.png the pins are labelled correctly but incorrectly wired in the schematics.

**Comment by alleybeachelectric** [comment]
Hello. The problem has been addressed. the C.H.I.P footprint pins were swapped in the original part. If you look at the pin numbers on the schematic, LRADC was matched with pin 12 of U14, and 3V3 was matched with pin 10, making it_technically_ work. We were aware of the pin swap during design, and addressed the issue today. Thanks for the good eyes!
